### ISSUE TITLE
Suggested changes/additions to the readme

### ISSUE THREAD

**Issue by StuartNewcombe** [datasciencecampus/Green_Spaces#10]
Couple of suggested changes/additions to the readme:

I'm assuming that the polygons mentioned throughout are the (shapes of the) individual gardens?
I think you're trying to keep it a bit vague to be clear that it could be used for different things too, rather than just for looking at vegetation in gardens; but I think it might be worth explicitly stating that, in this use case, the polygons are the shapes of the gardens you're looking at, so that the reader isn't thinking sort of...'what are these polygons? where do I get them from?'

Might be helpful if you made a simple diagram/flowchart to show/explain what you need to feed in (I think just the aerial images and geojsons to describe the polygons containing the gardens, or other areas you want to look at? (can you also input your own model to use for calculating the percentage, rather than using the neural net? (thinking then someone could plausibly use the same pipeline, using a different model, for looking at percentages of something else rather than % green in gardens - not sure quite what, mind...tree coverage in wooded areas...?)) and then what comes out as the output at the end. 

Couple of typos - 
- In the 'bulk analysis of geojson' section there's a typo in the word polygons in the following sentence:  “To run a bulk analysis using the analyse_polgons.py utility, instead use:”
- in the first sentence of the sift incomplete results section - 'machinesm'

**Comment by IanGrimstead** [comment]
https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2019/07/Figure_27-2.png

**Comment by IanGrimstead** [comment]
Intro paragraph explaining use case? then paragraph explaining how it is generic by design

**Comment by IanGrimstead** [comment]
Created branch `10-readme`
